name: LinkedIn Connect Bot

on:
  schedule:
    - cron: "0 12 * * *" # Runs every day at 12:00 UTC
  workflow_dispatch: # Manual trigger

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright browsers
        run: npx playwright install


      - name: Restore saved cookies
        run: echo "$LINKEDIN_COOKIES" > ./data/cookies.json
        env:
          LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }}

      - name: Run bot
        run: node scripts/connect.js
